### ISSUE TITLE
Error while deploying on heroku

### ISSUE THREAD

**Issue by Coherent5845** [ksssomesh12/tg-mirror-bot#11]
i get this error when i tried to deploy to heroku
![kdfdlljskd](https://user-images.githubusercontent.com/23115256/110250729-ddf23680-7fa2-11eb-9dfe-8818b4fb4c21.PNG)
i tried to copying the hroku.yml file from "deploy" folder to root, but it produced same error for me.

Help plz.

**Comment by ksssomesh12** [comment]
> i get this error when i tried to deploy to heroku
> ![kdfdlljskd](https://user-images.githubusercontent.com/23115256/110250729-ddf23680-7fa2-11eb-9dfe-8818b4fb4c21.PNG)
> i tried to copying the hroku.yml file from "deploy" folder to root, but it produced same error for me.
> 
> Help plz.

Did u deploy using the deploy_release_v1.*.tar.gz package?

**Comment by Coherent5845** [comment]
no, i just cloned the repo and made the necessary changes and then deployed with heroku cli, btw there was not any deploy_release_v1.*.tar.gz file in the repo.

or if you think that i did some fuck up, then plz help 

edit- i just realized that i had to download the release package instead of copying the repo, will try again after another attempt.

**Comment by ksssomesh12** [comment]
> no, i just cloned the repo and made the necessary changes and then deployed with heroku cli, btw there was not any deploy_release_v1.*.tar.gz file in the repo.
> 
> or if you think that i did some fuck up, then plz help
> 
> edit- i just realized that i had to download the release package instead of copying the repo, will try again after another attempt.

Yeah mate. The whole idea of the release package is to simplify the deploys. Just read the README.md file and you are good to  go.

**Comment by Coherent5845** [comment]
> > no, i just cloned the repo and made the necessary changes and then deployed with heroku cli, btw there was not any deploy_release_v1.*.tar.gz file in the repo.
> > or if you think that i did some fuck up, then plz help
> > edit- i just realized that i had to download the release package instead of copying the repo, will try again after another attempt.
> 
> Yeah mate. The whole idea of the release package is to simplify the deploys. Just read the README.md file and you are good to go.

thx it worked, will close the issue.
