### ISSUE TITLE
Add FOLDER Support when mirroring/cloning files to GDrive

### ISSUE THREAD

**Issue by soorajsprakash** [ksssomesh12/tg-mirror-bot#12]
## Use Case:
* When a user sync/mirror/clone a file to Gdrive, he specifies Folder into  which it should be mirrored.
* If a folder specified is not in Gdrive, then it creates the Folder specified and mirror file into that folder
    *  folder name should be case-insensitive.

_P.S: This would be helpful to organise folder at the mirroring/cloning stage_

## Code:
`/mirror <link> FolderName`

Eg: `/mirror magnet:?xt=urn:btih:975218B46971BC4E4019D20E9F68C72A57C622BE&dn=Mr.+Church+%282016%29+%5B720p%5D+%5BYTS%5D+%5BYIFY%5D&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.com%3A2710%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce MOVIES`

## Support Pics
* Usually this is what we do, and the bot msg is shown here
![image](https://user-images.githubusercontent.com/26853789/110339628-5feb6980-804e-11eb-8349-1543d87cd2a8.png)

* Now we specify **folder name** to the end of mirror command 
(see the keyword specified in the end of /mirror command)
![image](https://user-images.githubusercontent.com/26853789/110339997-c7a1b480-804e-11eb-820b-92035b436b96.png)

* expected output
Add the line to the bot's output message:
`Syncing to Folder: Movies`

**Comment by oneironaut2209** [comment]
A very good idea bro, I also really need this feature.

And instead of 
/mirror link folder name

This would also work
/mirror link folder id
where folder id can be from any other team drive also.

@ksssomesh12  Please add this feature if you can.

**Comment by oneironaut2209** [comment]
A very good idea bro, I also really need this feature.

And instead of 
/mirror <link> <folder name>

This would also work
/mirror <link> <folder id>
where folder id can be from any other team drive also.

@ksssomesh12  Please add this feature if you can.

**Comment by ksssomesh12** [comment]
> A very good idea bro, I also really need this feature.
> 
> And instead of
> /mirror link folder name
> 
> This would also work
> /mirror link folder id
> where folder id can be from any other team drive also.
> 
> @ksssomesh12 Please add this feature if you can.

It will be put in the development roadmap and as u stated the folder id can only be used and the folder name, because the google drive identifies folders by id and not name, and hence only folder id is specific to it.

**Comment by ksssomesh12** [comment]
This is implemented in the new repo `tgmb-beta`
