### ISSUE TITLE
Does it support Youtube Playlist Download Feature? and How to deploy on heroku?

### ISSUE THREAD

**Issue by askfriends** [ksssomesh12/tg-mirror-bot#14]
Seems like very helpful project.
I want to know does it support youtube playlist download feature? IF not can u add it with resolution selection?

Secondly can we deploy it to heroku without getting banned??

**Comment by ksssomesh12** [comment]
yes it does support youtube playlist downloads and res selection too. Check the README.md file, kindly. Try deploying on heroku for yourself. You have to see it to know it.

**Comment by askfriends** [comment]
> yes it does support youtube playlist downloads and res selection too. Check the README.md file, kindly. Try deploying on heroku for yourself. You have to see it to know it.

I am trying to deploy to heroku but coulndt suceed, so pleae help me.

When i run "python3 setup.py" it wont work, therefore i run "python3 setup.py install" is that correct?

here us what i did.

1. Edited and filled all required data in config.env
2. Downloaded credentials.json and put it in root
3. run this command "pip3 install -r requirements.txt"
4. Run this command but it wont work "python3 setup.py" so i run this instead "python3 setup.py install"
5. heroku login
heroku stack:set container --app your-mirror-bot
git init
git add .
git commit -m "initial commit"
heroku git:remote --app your-mirror-bot
git push heroku master

it gave error "! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/katper-tg-mirror-bot.git'"

**Comment by ksssomesh12** [comment]
> > yes it does support youtube playlist downloads and res selection too. Check the README.md file, kindly. Try deploying on heroku for yourself. You have to see it to know it.
> 
> I am trying to deploy to heroku but coulndt suceed, so pleae help me.
> 
> When i run "python3 setup.py" it wont work, therefore i run "python3 setup.py install" is that correct?
> 
> here us what i did.
> 
> 1. Edited and filled all required data in config.env
> 2. Downloaded credentials.json and put it in root
> 3. run this command "pip3 install -r requirements.txt"
> 4. Run this command but it wont work "python3 setup.py" so i run this instead "python3 setup.py install"
> 5. heroku login
>    heroku stack:set container --app your-mirror-bot
>    git init
>    git add .
>    git commit -m "initial commit"
>    heroku git:remote --app your-mirror-bot
>    git push heroku master
> 
> it gave error "! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'https://git.heroku.com/katper-tg-mirror-bot.git'"

Did  you use the deploy_release_v*.tar.gz package for deploying?

**Comment by askfriends** [comment]
> > > yes it does support youtube playlist downloads and res selection too. Check the README.md file, kindly. Try deploying on heroku for yourself. You have to see it to know it.
> > 
> > 
> > I am trying to deploy to heroku but coulndt suceed, so pleae help me.
> > When i run "python3 setup.py" it wont work, therefore i run "python3 setup.py install" is that correct?
> > here us what i did.
> > 
> > 1. Edited and filled all required data in config.env
> > 2. Downloaded credentials.json and put it in root
> > 3. run this command "pip3 install -r requirements.txt"
> > 4. Run this command but it wont work "python3 setup.py" so i run this instead "python3 setup.py install"
> > 5. heroku login
> >    heroku stack:set container --app your-mirror-bot
> >    git init
> >    git add .
> >    git commit -m "initial commit"
> >    heroku git:remote --app your-mirror-bot
> >    git push heroku master
> > 
> > it gave error "! [remote rejected] master -> master (pre-receive hook declined)
> > error: failed to push some refs to 'https://git.heroku.com/katper-tg-mirror-bot.git'"
> 
> Did you use the deploy_release_v*.tar.gz package for deploying?

no, i didnt use that, it was not mentioned anywhere in the readme.
do i need to extract that in root folder?
if possible please write all steps i need to follow to deploy to heroku.
Thanks a lot for the quick response.

**Comment by ksssomesh12** [comment]
Well mate. You need to read the README.md file again. It has all the detail in it. And if you are using Termux on Android, instead of a linux computer, there's nothing I can do to help you.

**Comment by askfriends** [comment]
> Well mate. You need to read the README.md file again. It has all the detail in it. And if you are using Termux on Android, instead of a linux computer, there's nothing I can do to help you.

im using windows pc, i can use replit.com or google colab to run linux commands.
i have already completed all steps like filling config file with all required info

Now Just let me know i have to extract deploy_release_v*.tar.gz package in the root alright?
and when i run python3 setup.py it gives following error
![Web capture_15-3-2021_141952_colab research google com](https://user-images.githubusercontent.com/2517219/111130928-91f25380-8599-11eb-9e81-10e582a207b3.jpeg)

**Comment by ksssomesh12** [comment]
Use WSL2 on Windows 10. [Extract the release package](https://github.com/ksssomesh12/tg-mirror-bot#cloning-and-setting-up-config-file). [And run the setup script after creating a virtual environment](https://github.com/ksssomesh12/tg-mirror-bot#setup).

**Comment by askfriends** [comment]
> Use WSL2 on Windows 10. [Extract the release package](https://github.com/ksssomesh12/tg-mirror-bot#cloning-and-setting-up-config-file). [And run the setup script after creating a virtual environment](https://github.com/ksssomesh12/tg-mirror-bot#setup).

ok, I installed WSL2 on windows 10, installed all required components and follow ur readme step by step.
Now when i run  these commands i get error
```
pipenv install -r requirements.txt
pipenv shell
```

also this commnad gives error again
`python3 setup.py`

Screenshots attached for reference.

![error2](https://user-images.githubusercontent.com/2517219/111305441-c4bf4900-8678-11eb-9ff5-a55f50dd0534.png)
![error1](https://user-images.githubusercontent.com/2517219/111305445-c721a300-8678-11eb-8ab8-02978fabecf4.png)

**Comment by ksssomesh12** [comment]
[See here](https://stackoverflow.com/questions/65548731/python-3-5-on-ubuntu-16-04-has-dict-syntax-error-for-installed-ackage) for what might have been causing the issue. Try upgrading python to version 3.8 or 3.9 and report back kindly. BTW, if you can dual boot ubuntu from your computer, then that would be advisable.

**Comment by askfriends** [comment]
> [See here](https://stackoverflow.com/questions/65548731/python-3-5-on-ubuntu-16-04-has-dict-syntax-error-for-installed-ackage) for what might have been causing the issue. Try upgrading python to version 3.8 or 3.9 and report back kindly. BTW, if you can dual boot ubuntu from your computer, then that would be advisable.

ok bru i have updated ubuntu to v20.
Now i could run these commands without error
```
pipenv install -r requirements.txt
pipenv shell
```

but when i run this command, it still gives error. python version is 3.8.8 as u can see in the SS below.
`python3 setup.py`

Now what could be the reason? btw im completely new to linux but im trying my best.
![error3](https://user-images.githubusercontent.com/2517219/111459789-f8fc3d80-873c-11eb-9629-35cd4a4b362d.png)


**UPDATE:**
Finally made it work!!!!
installed all missing modules manually by googlying.
Now i finished all steps, generated toke.pickle and pushed to heroku. But bot is not working.
Heroku logs say some files are missing.
I am attaching logs
[katper-tg-mirror-bot-logs-1615983417665.txt](https://github.com/ksssomesh12/tg-mirror-bot/files/6156291/katper-tg-mirror-bot-logs-1615983417665.txt)
![error4](https://user-images.githubusercontent.com/2517219/111469666-c5bfab80-8748-11eb-990a-d50b69188fa9.png)
![configenv](https://user-images.githubusercontent.com/2517219/111470233-7463ec00-8749-11eb-8c47-7603d87e270e.png)

**Comment by askfriends** [comment]
bro are u busy? waiting for ur response on above reply.

**Comment by ksssomesh12** [comment]
The log says the 'config.env' file is not found in the pushed Docker image. Did u build the image correctly? Try to redeploy on  heroku and send me the build log. BTW, 'config.env' file looks file. No issues with that. Seems the file is not copies when u built the image.

**Comment by askfriends** [comment]
> The log says the 'config.env' file is not found in the pushed Docker image. Did u build the image correctly? Try to redeploy on heroku and send me the build log. BTW, 'config.env' file looks file. No issues with that. Seems the file is not copies when u built the image.

Finally managed to pushed config.env by force push using this command
` git add -f config.env
`Then logs said credentials.json is missing so i did the same, force pushed that file too
` git add -f credentials.json
`
**Now bot is running fine and responding, but its not downloading files**, there is some error in the logs, i am attaching logs. Please have a look and suggest. Thanks

[katper-mirrorbot-new-logs-1616159564785.txt](https://github.com/ksssomesh12/tg-mirror-bot/files/6171312/katper-mirrorbot-new-logs-1616159564785.txt)

**Comment by ksssomesh12** [comment]
Thats the issue with 'token.pickle' file. Either the token file is expired or its not found. Do the same with this file as u did for config and credentials. git add -f token.pickle and commmit - push the change.

**Comment by askfriends** [comment]
> Thats the issue with 'token.pickle' file. Either the token file is expired or its not found. Do the same with this file as u did for config and credentials. git add -f token.pickle and commmit - push the change.

ok bro i did that, now logs dont show any error but still download wont start from magnet link or torrent file.
here is log file
[katper-mirrorbot-new-logs-1616181176910.txt](https://github.com/ksssomesh12/tg-mirror-bot/files/6173575/katper-mirrorbot-new-logs-1616181176910.txt)

**UPDATE:**
After using it for some time, its behaving strange.
Magnet download started and its 100% but now its stuck there, and not showing successfully uploaded msg.
For private torrent from private tracker, it doesnt start at all, while i downloaded that torrent from another bot and it downloaded without any problem. Here is the screenshot;

![bot1](https://user-images.githubusercontent.com/2517219/111836324-e4c06800-8917-11eb-9bae-836152b6fa49.png)

Added another torrent file from another private tracker, and here is the result.

![bot2](https://user-images.githubusercontent.com/2517219/111836386-002b7300-8918-11eb-9174-458a2960bb55.png)

Its stuck there. Now what could be the reason?
I have attached heroku logs too above.

**UPDATE:2**
After about 24 hours, its showing same screen, i also sent /status command and it shows same screen as shown above.

**Comment by askfriends** [comment]
bro awaiting ur reply.
and btw can we change user.agent value to something like qbittorrent?

**Comment by ksssomesh12** [comment]
The issue with upload is due to something with ur google drive token or ur project on google developers console has different scopes. For private trackers, u need to change the useragent in tgmb.helper.config.subproc.py and build the whole docker image manually.

**Comment by askfriends** [comment]
> tgmb.helper.config.subproc.py

Bot is working now, downloading from public trackers and youtube is working.
But i download from private trackers most of the time, so its necessary for me to change the user-agent.
Im new to this and dont know how to build the docker image, can u write steps and commands to build docker image or if you could make one for me? i will give u required details required in the process.
so far i understood i have to change this file and add values like shown in the screenshot below

![error5](https://user-images.githubusercontent.com/2517219/111973299-2ae81800-8b20-11eb-8e48-bc9613a86795.png)

But after than what should i do?

**Comment by askfriends** [comment]
**UPDATE:
Finally managed to fix it as u suggested, NOW bot is working as it should, i can download from private trackers, pulic trackers and also from youtube. Here is what i did (For all those who want to achieve this)**

Created a private repo
Duplicated this repo and pushed to private repo.
Added token.pickle, credentials.js files in the root.
Edited subproc.py as shown in the screenshot above.
Create heroku app and make it container
connect your github account in heroku deploy tab, and choose your private repo and deploy.
Thats it!

A Big thanks to @ksssomesh12 bro for guiding me through all the process and although i was noob but he thoroughly helped me.

**Comment by ksssomesh12** [comment]
Did you edit the Dockerfile or its still the same as it is in master branch? If its that then, your changes to subproc.py wont be persisted to the Docker Image. Use the Dockerfile from the dev branch and remove all lines after the '#MEGA SUPPORT' line including it, so that the last line would be the one starting with 'CMD'. This is the only way your changes will be persisted to the Docker Image. If you are concerned to know why, take a look at the Dockerfile in master branch; the bot python module is fetched and installed from the PyPI, instead of the source code files found in the project directory. TLDR, if you want to build your own Docker Images from source code then, you need to use the Dockerfile from dev branch as said above.

**Comment by askfriends** [comment]
> Did you edit the Dockerfile or its still the same as it is in master branch? If its that then, your changes to subproc.py wont be persisted to the Docker Image. Use the Dockerfile from the dev branch and remove all lines after the '#MEGA SUPPORT' line including it, so that the last line would be the one starting with 'CMD'. This is the only way your changes will be persisted to the Docker Image. If you are concerned to know why, take a look at the Dockerfile in master branch; the bot python module is fetched and installed from the PyPI, instead of the source code files found in the project directory. TLDR, if you want to build your own Docker Images from source code then, you need to use the Dockerfile from dev branch as said above.

No bro, its same as master branch.
i just copied docker file and heroku.yml from release and put them in root directory along with token.pickle and credentials.json files, then i connected the repo in heroku app and deployed, its working fine without any problems, my changes are still effective and i can download from private trackers.
I will keep that in mind and if any problem occurs i will do as u suggested.

**Comment by ksssomesh12** [comment]
> > Did you edit the Dockerfile or its still the same as it is in master branch? If its that then, your changes to subproc.py wont be persisted to the Docker Image. Use the Dockerfile from the dev branch and remove all lines after the '#MEGA SUPPORT' line including it, so that the last line would be the one starting with 'CMD'. This is the only way your changes will be persisted to the Docker Image. If you are concerned to know why, take a look at the Dockerfile in master branch; the bot python module is fetched and installed from the PyPI, instead of the source code files found in the project directory. TLDR, if you want to build your own Docker Images from source code then, you need to use the Dockerfile from dev branch as said above.
> 
> No bro, its same as master branch.
> i just copied docker file and heroku.yml from release and put them in root directory along with token.pickle and credentials.json files, then i connected the repo in heroku app and deployed, its working fine without any problems, my changes are still effective and i can download from private trackers.
> I will keep that in mind and if any problem occurs i will do as u suggested.

Any changes you make in config.env will persist, for instance the trackerslist to use. Any tinkering with the source code itself - that requires building your own docker image from scratch. Thats what i meant.

**Comment by ksssomesh12** [comment]
> > Did you edit the Dockerfile or its still the same as it is in master branch? If its that then, your changes to subproc.py wont be persisted to the Docker Image. Use the Dockerfile from the dev branch and remove all lines after the '#MEGA SUPPORT' line including it, so that the last line would be the one starting with 'CMD'. This is the only way your changes will be persisted to the Docker Image. If you are concerned to know why, take a look at the Dockerfile in master branch; the bot python module is fetched and installed from the PyPI, instead of the source code files found in the project directory. TLDR, if you want to build your own Docker Images from source code then, you need to use the Dockerfile from dev branch as said above.
> 
> No bro, its same as master branch.
> i just copied docker file and heroku.yml from release and put them in root directory along with token.pickle and credentials.json files, then i connected the repo in heroku app and deployed, its working fine without any problems, my changes are still effective and i can download from private trackers.
> I will keep that in mind and if any problem occurs i will do as u suggested.

Any changes you make in config.env will persist, for instance the trackerslist to use. Any tinkering with the source code itself - that requires building your own docker image from scratch. Thats what i meant.

**Comment by askfriends** [comment]
> > > Did you edit the Dockerfile or its still the same as it is in master branch? If its that then, your changes to subproc.py wont be persisted to the Docker Image. Use the Dockerfile from the dev branch and remove all lines after the '#MEGA SUPPORT' line including it, so that the last line would be the one starting with 'CMD'. This is the only way your changes will be persisted to the Docker Image. If you are concerned to know why, take a look at the Dockerfile in master branch; the bot python module is fetched and installed from the PyPI, instead of the source code files found in the project directory. TLDR, if you want to build your own Docker Images from source code then, you need to use the Dockerfile from dev branch as said above.
> > 
> > 
> > No bro, its same as master branch.
> > i just copied docker file and heroku.yml from release and put them in root directory along with token.pickle and credentials.json files, then i connected the repo in heroku app and deployed, its working fine without any problems, my changes are still effective and i can download from private trackers.
> > I will keep that in mind and if any problem occurs i will do as u suggested.
> 
> Any changes you make in config.env will persist, for instance the trackerslist to use. Any tinkering with the source code itself - that requires building your own docker image from scratch. Thats what i meant.

bro i dont undertand that and thats beyond my scope bcoz im not pro. All i wanted was to deploy it on heroku and be able to download torrents from private trackers and thats what is working for me.

**Comment by ksssomesh12** [comment]
> > > > Did you edit the Dockerfile or its still the same as it is in master branch? If its that then, your changes to subproc.py wont be persisted to the Docker Image. Use the Dockerfile from the dev branch and remove all lines after the '#MEGA SUPPORT' line including it, so that the last line would be the one starting with 'CMD'. This is the only way your changes will be persisted to the Docker Image. If you are concerned to know why, take a look at the Dockerfile in master branch; the bot python module is fetched and installed from the PyPI, instead of the source code files found in the project directory. TLDR, if you want to build your own Docker Images from source code then, you need to use the Dockerfile from dev branch as said above.
> > > 
> > > 
> > > No bro, its same as master branch.
> > > i just copied docker file and heroku.yml from release and put them in root directory along with token.pickle and credentials.json files, then i connected the repo in heroku app and deployed, its working fine without any problems, my changes are still effective and i can download from private trackers.
> > > I will keep that in mind and if any problem occurs i will do as u suggested.
> > 
> > 
> > Any changes you make in config.env will persist, for instance the trackerslist to use. Any tinkering with the source code itself - that requires building your own docker image from scratch. Thats what i meant.
> 
> bro i dont undertand that and thats beyond my scope bcoz im not pro. All i wanted was to deploy it on heroku and be able to download torrents from private trackers and thats what is working for me.

Ok then. The issue will be closed.
