### ISSUE TITLE
HOw to add multiple users.

### ISSUE THREAD

**Issue by Coherent5845** [ksssomesh12/tg-mirror-bot#16]
How can i give access to other user, instead of using the bot in a group.

**Comment by ksssomesh12** [comment]
you can send '/authorize #userid' to the bot

**Comment by Coherent5845** [comment]
ohk, i tried it but when i gave the command "/authorize 123456789" to the bot, and tried to access it with that account, but it didnt worked.

if you are confused what i was trying to say, then i will explain it once more.

For example, the owner if the bot can access the bot individually but other users cannot, thats why we have to add the bot to a group to give multiple users access, but i have multiple tg accounts and i also want to access the bot individually, but i am unable to do so.

in the lizzy repo, we have to add and authorized.txt called file to give users, to access the bot individually.

**Comment by ksssomesh12** [comment]
> ohk, i tried it but when i gave the command "/authorize 123456789" to the bot, and tried to access it with that account, but it didnt worked.
> 
> if you are confused what i was trying to say, then i will explain it once more.
> 
> For example, the owner if the bot can access the bot individually but other users cannot, thats why we have to add the bot to a group to give multiple users access, but i have multiple tg accounts and i also want to access the bot individually, but i am unable to do so.
> 
> in the lizzy repo, we have to add and authorized.txt called file to give users, to access the bot individually.

U can utilise the same method as that of lzzy's repo's. But as of now, dynamic config doesn't support using 'authorized.txt'. In case of static config, it works fine.
