### ISSUE TITLE
Shortener issue

### ISSUE THREAD

**Issue by ghost** [ksssomesh12/tg-mirror-bot#17]
When i din't use telegraph, Shortener in /list command is not working, but if use telegraph is working

**Comment by ksssomesh12** [comment]
> When i din't use telegraph, Shortener in /list command is not working, but if use telegraph is working

Yeah, it doesnt work and provides direct drive links.

**Comment by ghost** [comment]
> > When i din't use telegraph, Shortener in /list command is not working, but if use telegraph is working
> 
> Yeah, it doesnt work and provides direct drive links.

Also when i do `/list .` it said ERROR - Message_too_long

**Comment by ksssomesh12** [comment]
> > > When i din't use telegraph, Shortener in /list command is not working, but if use telegraph is working
> > 
> > 
> > Yeah, it doesnt work and provides direct drive links.
> 
> Also when i do `/list .` it said ERROR - Message_too_long

Now, thats because the search results are longer than the character limit for a single text message on Telegram. In that case, you need to use telegraph.
