### ISSUE TITLE
To Add Cancel Command before the GID

### ISSUE THREAD

**Issue by deadsec45** [ksssomesh12/tg-mirror-bot#18]
Add Cancel Command Before the GID in the Download Status Message would make canceling stuff every easy and convenient

**Comment by ksssomesh12** [comment]
> Add Cancel Command Before the GID in the Download Status Message would make canceling stuff every easy and convenient

Check [this commit](https://github.com/ksssomesh12/tg-mirror-bot/commit/983464e63d52bc39cff58813208d0282406da2dc).

**Comment by deadsec45** [comment]
Thanks Man

**Comment by deadsec45** [comment]
Looks great to me . All the Small And Shuttle Changes are good
