### ISSUE TITLE
Staging Branch Authorized.txt doesnt work

### ISSUE THREAD

**Issue by deadsec45** [ksssomesh12/tg-mirror-bot#26]
Reason seems to be the bot supports authorized_chats.txt and not authorized.txt

so please make the required changes

**Comment by deadsec45** [comment]
It works in the Master Branch ( I only tried it with Dynamic Config and authorized_chats.txt

**Comment by ksssomesh12** [comment]
Maybe try again?? It works fine for me. Try the staging branch.
