### ISSUE TITLE
Cant download YouTube playlist having 90 videos

### ISSUE THREAD

**Issue by askfriends** [ksssomesh12/tg-mirror-bot#31]
Im trying to download a playlist whih has 90 videos, it starts downloading but then shows error. can u fix it or update ytdl to latest?
here is the link

https://www.youtube.com/playlist?list=PLgirwYDDPtS1fWzj8IBUxjN07pF9Y9wdg

i have also opened an issue on ytdl here
https://github.com/ytdl-org/youtube-dl/issues/29110#issuecomment-847290719

someone reported he can download all 90 videos on machine so it may be bot related issue, so  kindly have a look

**Comment by ksssomesh12** [comment]
This issue is solved or u closed it for some other reason?

**Comment by askfriends** [comment]
> This issue is solved or u closed it for some other reason?

Yes its solved i dont know how, I didnt do anything but just keep trying and it successfully download all videos. I havnt tried again or another link, so hopefully it will not do any hussle next time.

**Comment by ksssomesh12** [comment]
Cheers then. Feel free to reopen the issue, if it happens again.
