### ISSUE TITLE
tgmb-canary

### ISSUE THREAD

**Issue by ksssomesh12** [ksssomesh12/tg-mirror-bot#34]

**Comment by CodexNova** [comment]
i want to test it. let's see how it works

**Comment by ksssomesh12** [comment]
Well, then, let me clean it up for some time, then I'll make it public. Also, there are no instructions on how to deploy using this repo. So, unless u can understand python, u cant deploy and test it until README.md is filled up

**Comment by oneironaut2209** [comment]
I am also ready to test. I will test on heroku and vps both.

**Comment by akibithi** [comment]
I want to test, can I deploy it in heroku?

**Comment by ksssomesh12** [comment]
U can deploy it on heroku, as for myself, I test by deploying on heroku too. But, as I said earlier, functionality is very limited as of now. And also needs some cleanup. So, within another weeks's time, the bot repo will be made public, for u people to test and provide feedback.

**Comment by ksssomesh12** [comment]
Check this out: https://github.com/ksssomesh12/tgmb-temp

**Comment by akibithi** [comment]
brother, what's the update?

**Comment by bolavefasfas** [comment]
i want to test it on heroku & on vps

**Comment by ksssomesh12** [comment]
> i want to test it on heroku & on vps

Well, go ahead and deploy it.

**Comment by askfriends** [comment]
How about adding support for cloning MEGA support?
its already available in many repos and really helpful

**Comment by ksssomesh12** [comment]
> How about adding support for cloning MEGA support?
> its already available in many repos and really helpful

Its wip. Will be added soon. Stay Tuned !

**Comment by ksssomesh12** [comment]
> How about adding support for cloning MEGA support?
> its already available in many repos and really helpful

Update: MEGA support is being worked on in [this branch](https://github.com/ksssomesh12/tgmb-beta/tree/mega-dl) actively. As of now, you can download single files only; not folders, just yet.

**Comment by ksssomesh12** [comment]
Update: MEGA Support is fully implemented now in master branch. Uploads to MEGA will be enabled later some time.

**Comment by askfriends** [comment]
bro i have set Use_Service_Accounts to true, now where to put SAs?
there is nothing mentioned in Readme
